AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Step Functions for the Orchestrator
Parameters:
  Grupo:
      Type: String
      Description: 'Grupo de proyecto'
      Default: Auna
  AppEnv:
    Default: dev
    Type: String
    Description: 'environment (lowercase only), ex: dev, qas, prd'
    AllowedValues:
      - qas
      - dev
      - prd
  Env:
    Default: DEV
    Type: String
    Description:  'environment (uppercase only), ex: dev, qas, prd'
    AllowedValues:
      - QAS
      - DEV
      - PRD
  ProjectName:
    Type: String
    Description: Projects's name that will be used on Resources (lower case)
    Default: auna      
  BucketArtifacts:
      Type: String
      Description: 'bucket artifacts'
      Default: auna-lake-artifacts
  BucketLanding:
      Type: String
      Description: 'bucket landing'
      Default: auna-lake-landing
  BucketRaw:
      Type: String
      Description: 'bucket raw'
      Default: auna-lake-raw
Resources:
  StateMachineRes:
    Type: AWS::StepFunctions::StateMachine
    DeletionPolicy: 'Delete'
    Properties:
      StateMachineName: !Sub sf-lake-integrador-${AppEnv}
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/role-producer-${ProjectName}-${AppEnv}
      DefinitionString:
        !Sub |
        {
          "Comment": "A description of my state machine",
          "StartAt": "Choice",
          "States": {
            "Choice": {
              "Type": "Choice",
              "Choices": [
                {
                  "Not": {
                    "Variable": "$.data",
                    "IsPresent": true
                  },
                  "Next": "SNS FAILED"
                }
              ],
              "Default": "Glue Job Raw"
            },
            "Glue Job Raw": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun.sync",
              "Parameters": {
                "JobName": "JobRawLake",
                "Arguments": {
                  "--data.$": "$.data"
                }
              },
              "Next": "Glue Job Analytics",
              "Catch": [
                {
                  "ErrorEquals": [
                    "States.ALL"
                  ],
                  "Next": "SNS FAILED"
                }
              ],
              "ResultPath": "$.glue_job_raw"
            },
            "SNS FAILED": {
              "Type": "Task",
              "Resource": "arn:aws:states:::sns:publish",
              "Parameters": {
                "TopicArn": "arn:aws:sns:us-east-1:279224823134:sns-integrator-notify-alert-dev",
                "Message": {
                  "Message.$": "$.Cause"
                }
              },
              "Next": "Fail"
            },
            "Fail": {
              "Type": "Fail"
            },
            "Glue Job Analytics": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun.sync",
              "Parameters": {
                "JobName": "JobLakeAnalytic",
                "Arguments": {
                  "--data.$": "$.data"
                }
              },
              "Catch": [
                {
                  "ErrorEquals": [
                    "States.ALL"
                  ],
                  "Next": "SNS FAILED"
                }
              ],
              "Next": "Success",
              "ResultPath": "$.glue_job_analytics"
            },
            "Success": {
              "Type": "Succeed"
            }
          }
        }
